YOUR_API_ID = "25552048"
YOUR_API_HASH = "77b6dfd240d6156e074b95fc462a2a16"
YOUR_PHONE_NUMBER = "+31626469088"
MESSAGE = "🌲 WIET 🌲 \n\n 🍀🇺🇸Cali Gelato Cake Wiet🇺🇸🍀 \n ✅Zeer Sterke Geur en Effect \n 100g = €400 \n 1000g = €3900 \n\n 🍀AMNESIA HAZE WIET🍀 \n ✅Goed effect en Compact \n 100g = €400 \n 1000g = €3900 \n\n 🦠OG Kush Indica WIET🦠 \n ✅Zoete smaak \n 100g = €390 \n 1000g = €3700 \n\n 🌲Bubble Gum Kush Indica🌲 \n ✅Zoete smaak \n 100g = €380 \n 1000g = €3700 \n\n 🌲OG of Bubble Indica🌲 \n ✅Kleine Toppen \n 100g = €280 \n 1000g = €2700 \n\n 🍁SPAANSE AMNESIA WEED 🍁 \n ✅Grote toppen \n 100g = €250 \n 1000g = €2300 \n\n 🍁SPAANSE AMNESIA WEED 🍁 \n ✅Compacte toppen \n 100g = €240 \n 1000g = €2200 \n\n 🌳NL Haze GRUIS, FIJN🌳 \n 100g = 50 \n 1000g = 300 \n\n 🍫HASJ🍫 \n\n 🍫Lemon Hasj Commerciële🍫 \n ✅Lichte, Hasj structuur \n 100g = €180 \n 1000g = €1500 \n\n 🍫Lemon Hasj Commerciële🍫 \n ✅Donkere, wiethasj structuur \n 100g = €180 \n 1000g = €1500 \n\n PB voor beeldmateriaal ✍ \n Ophalen in Amsterdam❌"
GROUPS= '''@FraudeDesk
@koopenswipehandelsgroep
@FraudeursTelegram
@ALLESHANDELL
@Twentestraatmarktt
@adamseonderwereld
@HandelMiddenNederland
@rotterdamsemarktplaats
@telemarktplaats
@hardewerker22
@GeldOmloopAmsterdam2
@ne9en7evenhandel
@softdrugsbredatilburg
@fgameverkoop
@allenFRAUDEenOPLICHTING
@AmsterdamhandelUtrecht
@AmsterdamHandelXXX
@handelally
@BredaOosterhout
@alleshandelalleen
@HandeIsgroep
@chosselline
@handelkings
@handelsgroeppp
@rotterdamsemarkt
@groeps
@handelgebied
@GARFIELDSFRAUDE
@markplaats2018
@OpsporingVerzochtt
@HandelTelegramNL9
@nimmaradaralarm
@handelleeuwarden
@DrieMMCzwolle
@politiearnhem
@telemarkt070
@Silkroadmarkt
@ADAMSEHANDEL
@bussinesg
@handelenschede
@theblackmarket
@bonknl
@tilburgviraal
@Utrecht030Handel
@denboschh
@handelswipers
@Brieven
@LegaleHandel
@INGbankNL
@HandelWandell
@wiethasjamsterdam
@HollandseHandelgroep
@HandelTelegram
@HandelsmarktXXL
@drugwapens
@YoungHandel
@eindjebrakkahandel
@ChoppersGG
@handelbreda
@marktplaats_chat
@steroidsantwerp
@groothandell
@Vuurwerkshop
@Roosendaal
@HANDELN
@VerkoopHandel
@handelkopvnoordholland
@fgamers01
@handelsmarktx
@leipzigdrogen
@bremengeld
@dortmundhaze
@neurenbergmarktplatz
@kolndrogen
@essenmarktplatz
@essenmarkt
@berlinteile
@berlingeld
@berlinmarktplatz
@nlhaze
@telemarketNL
@telezwartemarkt
@HandelZakenNL2
@aangifte
@handelsplek
@VerkoopGroepNL
@Leeuwardendrugs
@HandelMarktNL
@handelmaastricht
@handelzaken
@handelsmannen
@handelendoejezo
@wietmarkt
@grasstore
@marktplaatsx
@marktplaatsxxll
@handelxxl
@wapenhandeleu
@handelennederland
@handelenpraat
@handelvraagaanbod
@handelenfraude
@handeleegroep
@dusseldorfmarktplatz
@PLAATSDELICTX
@bezorgers020
@FraudeBestrijdingChat
@Alleshandel
@HandelsGroep247
@handelgroep
@HANDELTG
@handelAmstelveen
@handelarenbijeen
@fraudelocatie2
@handelamsterdam020
@HandelEnVerdienen
@handelbrabanttt
@Handeldrugs
@handelfrieslandp
@handelforumdrachten
@HandelHollandia
@handeling070
@HandelOostNederland
@HandelWestBrabant
@alleshandel247
@AllesHandeltjesss
@marktplaatsvanTG
@TeleMarkt
@DrugKoden
@BelgieKust
@FgameChat
@BRENGSNELJEVIS
@brengjekkvisjes
@Handelvanhenk
@groothandel1
@groothandel
@HandelNL
@Munchenmarkt
@antwerpenh
@belgieh
@belgiebussines
@antwerpenbussines
@kippensoep1
@bonkersworldwide
@noscamallowed
@StackkkzBonkersBijEen
@fraudehandelnl
@bonkenswipe
@MediaMarkt1
@MegaHandel1
@Handelonline
@Handelgond
@groepschat404
@niffofownw
@hollandsehhandel
@zwartehandelnederland
@marktplatz_deutschland
@handelstrijderss
@SwipeOuwe
@noordnederlandhandel0
@fwerkers247
@FlevoHandel
@handelnoordkop
@snelhandel
@snelheidamsterdam020
@Husselhard
@wiethandeltje
@scammershometown
@Hollandsehandel
@handelsgrond
@belgiumfraud
@InfoAvondklok
@joindiekankerding
@werkers22'''
